# frozen_string_literal: true

Category.create(name: 'アクション')
Category.create(name: 'アドベンチャー')
Category.create(name: 'アニメ')
Category.create(name: 'SF')
Category.create(name: 'ホラー')
Category.create(name: 'コメディ')
Category.create(name: 'ミステリー')
Category.create(name: 'サスペンス')
Category.create(name: 'ロマンス')
Category.create(name: 'ファンタジー')
Category.create(name: 'ミュージカル')
Category.create(name: 'ドキュメンタリー')
Category.create(name: 'スポーツ')
Category.create(name: '時代劇')
Category.create(name: '任侠')
Category.create(name: 'バイオレンス')
Category.create(name: 'その他')
